import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  glowBackground: {
    position: "absolute",
    top: -50,
    left: -100,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(139, 92, 246, 0.08)",
  },
  scrollContent: {
    paddingTop: 60,
    paddingBottom: 40,
  },
  header: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 28,
    fontFamily: "Raleway_700Bold",
    marginBottom: 4,
  },
  headerSubtitle: {
    color: "#8b5cf6",
    fontSize: 16,
    fontFamily: "Raleway_600SemiBold",
    marginBottom: 16,
  },
  statsPill: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statsPillText: {
    color: "#ccc",
    fontSize: 12,
    fontFamily: "Raleway_600SemiBold",
  },
  searchBoxContainer: {
    paddingHorizontal: 24,
    marginBottom: 32,
  },
  searchInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(20, 20, 25, 0.8)",
    height: 60,
    borderRadius: 16,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "rgba(139, 92, 246, 0.4)",
    shadowColor: "#8b5cf6",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 15,
    fontFamily: "Raleway_400Regular",
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 40,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 16,
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Raleway_700Bold",
  },
  vaultGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  vaultCard: {
    width: (width - 48 - 12) / 2,
    backgroundColor: "rgba(20,20,25,0.6)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  vaultIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  vaultIcon: {
    fontSize: 16,
  },
  vaultInfo: {},
  vaultCount: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Raleway_700Bold",
    marginBottom: 2,
  },
  vaultTitle: {
    color: "#8a8a8a",
    fontSize: 12,
    fontFamily: "Raleway_600SemiBold",
  },
  fragmentsList: {
    gap: 16,
  },
  fragmentCard: {
    backgroundColor: "rgba(20,20,25,0.6)",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  fragmentTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  fragmentBadge: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  fragmentBadgeText: {
    color: "#34d399",
    fontSize: 10,
    fontFamily: "Raleway_700Bold",
    letterSpacing: 1,
  },
  fragmentSource: {
    color: "#666",
    fontSize: 12,
    fontFamily: "Raleway_600SemiBold",
  },
  fragmentQuote: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Raleway_400Regular",
    fontStyle: "italic",
    lineHeight: 24,
    marginBottom: 20,
  },
  playClipButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 44,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(139, 92, 246, 0.3)",
  },
  playClipIcon: {
    color: "#fff",
    fontSize: 10,
    marginRight: 8,
  },
  playClipText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Raleway_700Bold",
  },
});
