import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  glowBackground: {
    position: "absolute",
    top: -100,
    right: -100,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(109, 93, 252, 0.05)",
  },
  scrollContent: {
    paddingTop: 60,
    paddingBottom: 140,
  },
  heroContainer: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 10,
  },
  heroGreeting: {
    color: "#fff",
    fontSize: 28,
    fontFamily: "Raleway_700Bold",
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 32,
  },
  searchContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  searchPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    height: 52,
    borderRadius: 26,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  searchIcon: {
    fontSize: 14,
    marginRight: 12,
  },
  searchText: {
    color: "#777",
    fontSize: 14,
    fontFamily: "Raleway_400Regular",
  },
  heroCard: {
    borderRadius: 24,
    padding: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(20, 20, 25, 0.4)",
  },
  heroAmbientGlow: {
    position: "absolute",
    bottom: -40,
    right: -40,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(139, 92, 246, 0.15)",
    opacity: 0.8,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  heroBadge: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  heroBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontFamily: "Raleway_600SemiBold",
  },
  heroTimeText: {
    color: "#999",
    fontSize: 12,
    fontFamily: "Raleway_600SemiBold",
  },
  heroTitle: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Raleway_700Bold",
    lineHeight: 28,
    marginBottom: 12,
  },
  heroDescription: {
    color: "#8a8a8a",
    fontSize: 14,
    fontFamily: "Raleway_400Regular",
    lineHeight: 20,
    marginBottom: 24,
  },
  heroButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
    overflow: "hidden",
  },
  heroButtonIcon: {
    color: "#fff",
    fontSize: 12,
    marginRight: 8,
  },
  heroButtonText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Raleway_700Bold",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Raleway_700Bold",
  },
  viewAllText: {
    color: "#5c8df6",
    fontSize: 13,
    fontFamily: "Raleway_600SemiBold",
  },
  subCard: {
    width: 140,
  },
  subImage: {
    width: 140,
    height: 140,
    borderRadius: 16,
    marginBottom: 12,
    backgroundColor: "#111",
  },
  subBadge: {
    position: "absolute",
    bottom: 40,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  subBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontFamily: "Raleway_600SemiBold",
  },
  subTitle: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Raleway_600SemiBold",
  },
  subUnderline: {
    width: 40,
    height: 2,
    backgroundColor: "#8b5cf6",
    marginTop: 6,
    borderRadius: 1,
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tagPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
  },
  tagDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#8b5cf6",
    marginRight: 8,
  },
  tagText: {
    color: "#ddd",
    fontSize: 13,
    fontFamily: "Raleway_600SemiBold",
  },
  insightsList: {
    gap: 16,
  },
  insightCard: {
    backgroundColor: "rgba(20,20,25,0.4)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 20,
    padding: 20,
  },
  insightHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  insightAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
    backgroundColor: "#333",
  },
  insightAuthorInfo: {
    flex: 1,
  },
  insightAuthor: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Raleway_700Bold",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  insightSource: {
    color: "#8a8a8a",
    fontSize: 11,
    fontFamily: "Raleway_400Regular",
  },
  insightMenuIcon: {
    color: "#666",
    fontSize: 18,
  },
  insightQuote: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Raleway_400Regular",
    fontStyle: "italic",
    lineHeight: 24,
    marginBottom: 24,
  },
  insightScrubberContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  scrubberIconPlaceholder: {
    width: 24,
    height: 24,
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  scrubberLine: {
    flex: 1,
    height: 2,
    backgroundColor: "rgba(255,255,255,0.1)",
    marginRight: 16,
    justifyContent: "center",
  },
  scrubberProgress: {
    position: "absolute",
    left: 0,
    width: "40%",
    height: "100%",
    backgroundColor: "#8b5cf6",
  },
  scrubberHandle: {
    position: "absolute",
    left: "40%",
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
    transform: [{ translateX: -4 }],
  },
  debateCard: {
    backgroundColor: "rgba(20,20,25,0.4)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 20,
    padding: 24,
  },
  debateTopic: {
    color: "#666",
    fontSize: 10,
    fontFamily: "Raleway_700Bold",
    letterSpacing: 1,
    marginBottom: 4,
  },
  debateTitle: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Raleway_700Bold",
    marginBottom: 20,
  },
  debateColumns: {
    flexDirection: "row",
  },
  debateSide: {
    flex: 1,
  },
  debateProLabel: {
    color: "#8b5cf6",
    fontSize: 12,
    fontFamily: "Raleway_700Bold",
    marginBottom: 8,
  },
  debateConLabel: {
    color: "#f472b6",
    fontSize: 12,
    fontFamily: "Raleway_700Bold",
    marginBottom: 8,
  },
  debateText: {
    color: "#ccc",
    fontSize: 13,
    fontFamily: "Raleway_400Regular",
    lineHeight: 20,
  },
  debateDivider: {
    width: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    marginHorizontal: 16,
  },
  feedCard: {
    borderRadius: 20,
    padding: 20,
    overflow: "hidden",
  },
  feedCardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  feedCardImage: {
    width: 48,
    height: 48,
    borderRadius: 12,
    marginRight: 16,
  },
  feedCardTitleContainer: {
    flex: 1,
  },
  feedCardContext: {
    color: "#a1a1aa",
    fontSize: 12,
    fontFamily: "Raleway_600SemiBold",
    marginBottom: 4,
  },
  feedCardTitle: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Raleway_700Bold",
  },
  feedCardSnippet: {
    color: "#e4e4e7",
    fontSize: 14,
    fontFamily: "Raleway_400Regular",
    lineHeight: 22,
  },
  feedCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  footerTime: {
    color: "#71717a",
    fontSize: 12,
    fontFamily: "Raleway_600SemiBold",
  },
  playButtonMini: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  playButtonMiniIcon: {
    color: "#fff",
    fontSize: 14,
    marginLeft: 3,
  },
  aiAskContainer: {
    marginHorizontal: 24,
    marginTop: 10,
    marginBottom: 60,
    borderRadius: 28,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(139, 92, 246, 0.6)",
    backgroundColor: "rgba(139, 92, 246, 0.1)",
    shadowColor: "#8b5cf6",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  aiAskInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    height: 56,
  },
  aiAskIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  aiAskInput: {
    flex: 1,
    color: "#fff",
    fontSize: 15,
    fontFamily: "Raleway_400Regular",
  },
  aiAskMic: {
    fontSize: 18,
    color: "#a1a1aa",
    marginLeft: 12,
  }
});