import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  noiseOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
    opacity: 0.05,
    pointerEvents: "none",
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  iconText: {
    color: "#fff",
    fontSize: 20,
    lineHeight: 24,
  },
  logoContainer: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  logoGlow: {
    position: "absolute",
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(139, 92, 246, 0.5)",
    shadowColor: "#8b5cf6",
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
  },
  logoText: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Raleway_700Bold",
    zIndex: 1,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  mediaContainer: {
    paddingHorizontal: 24,
    alignItems: "center",
    marginBottom: 40,
  },
  artworkWrapper: {
    width: width - 48,
    height: width - 48,
    marginBottom: 32,
    position: "relative",
  },
  artworkGlow: {
    position: "absolute",
    top: 20,
    left: 20,
    right: 20,
    bottom: -10,
    backgroundColor: "rgba(139, 92, 246, 0.4)",
    // Note: React Native doesn't support 'filter' out of the box in the same way web does. 
    // We rely on shadow properties for glow, but keeping it as a styled box behind the image works well enough.
    shadowColor: "#8b5cf6",
    shadowOpacity: 0.5,
    shadowRadius: 30,
    borderRadius: 20,
  },
  artwork: {
    width: "100%",
    height: "100%",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  metadata: {
    width: "100%",
    marginBottom: 32,
  },
  episodeTitle: {
    color: "#fff",
    fontSize: 22,
    fontFamily: "Raleway_700Bold",
    marginBottom: 8,
    lineHeight: 28,
  },
  hostName: {
    color: "#8b5cf6",
    fontSize: 16,
    fontFamily: "Raleway_600SemiBold",
  },
  progressContainer: {
    width: "100%",
    marginBottom: 32,
  },
  progressBarBg: {
    width: "100%",
    height: 6,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 3,
    flexDirection: "row",
    alignItems: "center",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  progressThumb: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#fff",
    marginLeft: -6,
    shadowColor: "#fff",
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  timeText: {
    color: "#8a8a8a",
    fontSize: 12,
    fontFamily: "Raleway_400Regular",
    fontVariant: ["tabular-nums"],
  },
  controlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "70%",
  },
  controlButton: {
    padding: 10,
  },
  controlIconSmall: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Raleway_600SemiBold",
  },
  playButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  playIcon: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Raleway_700Bold",
    letterSpacing: 2,
  },
  aiSection: {
    paddingHorizontal: 24,
  },
  aiHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: "rgba(139, 92, 246, 0.1)",
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(139, 92, 246, 0.3)",
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#8b5cf6",
    marginRight: 8,
    shadowColor: "#8b5cf6",
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  aiHeaderText: {
    color: "#b99eff",
    fontSize: 11,
    fontFamily: "Raleway_700Bold",
    letterSpacing: 1.5,
  },
  liveFeedContainer: {
    gap: 8,
    backgroundColor: "rgba(10,10,15,0.8)",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  logItem: {
    marginBottom: 4,
  },
  logText: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Courier",
    lineHeight: 18,
  },
  logTimestamp: {
    color: "#666",
  },
  logType: {
    color: "#b99eff",
  },
  logTypeInfo: {
    color: "#60a5fa",
  },
  logTypeSuccess: {
    color: "#34d399",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  menuContainer: {
    width: "100%",
    backgroundColor: "rgba(20,20,25,0.95)",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  menuTitle: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Raleway_700Bold",
    marginBottom: 20,
    textAlign: "center",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  menuIcon: {
    fontSize: 20,
    marginRight: 16,
    width: 28,
    textAlign: "center",
  },
  menuItemText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Raleway_600SemiBold",
  },
  menuDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    marginVertical: 4,
  },
});
